### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by hybridtheorist** [leethomason/OpenSaber#12]
Thanks for adding the wiring diagram to readme.md, I will clean up your drawing and send you a nice one. Could you please also show how to connect the speaker and DotStar to the prop shield?  I will create the clean design based on your drawing as well and send the drawing back to you. - Bo

**Comment by leethomason** [comment]
@hybridtheorist Thanks! A cleaned up version would be great. The Prop Shield wiring I didn't include, just because it's so literal.  Check out: http://www.pjrc.com/store/propshield_pinout.png. On the left, the speaker wires connect to Speaker+ and Speaker-. On the right, G-C-D-5 are the 4 standard lines for a DotStar LED. It wires straight up. (The DotStars are used for UI: power meter, volume meter, etc. as well as an internal crystal. They are completely optional, and not to be confused with the blade LED.)
